[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
PySide6 = "^6.7.2"
PySide6-QtAds = "^4.3.0.2"
timer = "^0.3.0"
consult-interface = {path = "../consult-interface", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
